---
# Choose: 'apache' for LAMP or 'nginx' for LEMP
web_server: apache
db_server: mysql  

web_server_package: "{{ 'apache2' if web_server == 'apache' else 'nginx' }}"
web_server_service: "{{ 'apache2' if web_server == 'apache' else 'nginx' }}"
web_server_conf: "{{ 'apache.conf.j2' if web_server == 'apache' else 'nginx.conf.j2' }}"
web_server_conf_dest: "{{ '/etc/apache2/apache2.conf' if web_server == 'apache' else '/etc/nginx/nginx.conf' }}"

db_server_package: mysql-server
db_server_service: mysql

php_packages:
  - php
  - php-mysql

